const ms=[{"id": "mst0bef1uot6i", "region": "kalocsa", "complexity": "Egyszerű", "type": "virág, rózsa", "name": "Kalocsai rózsa", "color": "piros, vörös", "desc": "", "svg": "assets/mst0bef1uot6i.svg", "png": null, "gcode": "gcode/mst0bef1uot6i.gcode"}, {"id": "mst0diyk81gvy", "region": "Mezőkövesd, Matyó", "complexity": "Egyszerű", "type": "virág, tulipán", "name": "Matyó Tulipán", "color": "Piros, sárga, vörös", "desc": "", "svg": "assets/mst0diyk81gvy.svg", "png": null, "gcode": null}, {"id": "mst0i4odzr6y4", "region": "Mezőkövesd, Matyó", "complexity": "Közepes", "type": "Virág, csokor, összetett motívum", "name": "Forgórózsás csokor", "color": "piros, sárga, kák, zöld", "desc": "", "svg": "assets/mst0i4odzr6y4.svg", "png": null, "gcode": null}, {"id": "mst0jtxjgmhkv", "region": "KAlocsa", "complexity": "Közepes", "type": "virág, szár", "name": "KAlocsai rózsa szárral", "color": "piros, vörös, sötétzöls, világoszöld", "desc": "", "svg": "assets/mst0jtxjgmhkv.svg", "png": null, "gcode": "gcode/mst0jtxjgmhkv.gcode"}, {"id": "mst0nyucink7j", "region": "kalocsa", "complexity": "Egyszerű", "type": "rózsa, virág", "name": "kalocsdai rózsa rózsaszín", "color": "rozsaszín, világosrozsaszín", "desc": "", "svg": "assets/mst0nyucink7j.svg", "png": null, "gcode": null}, {"id": "mst0pirdtr5zg", "region": "Mezőkövesd, Matyó", "complexity": "Közepes", "type": "Virág, Levél", "name": "Harangvirág, dupla macskatalp", "color": "piros, zöld, vörös, sárga", "desc": "", "svg": "assets/mst0pirdtr5zg.svg", "png": null, "gcode": "gcode/mst0pirdtr5zg.gcode"}];
const esc=s=>String(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function fill(id,a,first){document.getElementById(id).innerHTML='<option value="">'+first+'</option>'+a.map(x=>'<option>'+esc(x)+'</option>').join('')}
function render(){
 const q=document.getElementById("search").value.toLowerCase(),r=regionFilter.value,c=complexityFilter.value,t=typeFilter.value;
 document.getElementById("catalog").innerHTML=ms.filter(m=>(!q||[m.name,m.region,m.type,m.color].join(" ").toLowerCase().includes(q))&&(!r||m.region===r)&&(!c||m.complexity===c)&&(!t||m.type===t)).map(m=>`<article class="card" onclick="openM('${m.id}')"><div class="art">${m.svg?`<img src="${m.svg}">`:'<span>Nincs SVG</span>'}</div><div class="tag">${esc(m.region)}</div><h3>${esc(m.name)}</h3><div class="small">${esc(m.type)} · ${esc(m.color)}</div><div class="small">Komplexitás: ${esc(m.complexity)}</div></article>`).join('');
}
function openM(id){const m=ms.find(x=>x.id===id);document.getElementById("detail").innerHTML=`<div class="detail"><div>${m.svg?`<img src="${m.svg}">`:''}${m.png?`<p><b>Kiegészítő PNG</b><br><img src="${m.png}"></p>`:''}</div><div><div class="tag">${esc(m.region)}</div><h2>${esc(m.name)}</h2><p><b>Komplexitás:</b> ${esc(m.complexity)}<br><b>Típus:</b> ${esc(m.type)}<br><b>Szín:</b> ${esc(m.color)}</p><p>${esc(m.desc)}</p>${m.gcode?`<a class="btn" href="${m.gcode}" download>G-code letöltése</a>`:'<p>Nincs G-code ehhez a mintához.</p>'}</div></div>`;document.getElementById("modal").hidden=false}
function closeM(){document.getElementById("modal").hidden=true}
const rs=[...new Set(ms.map(m=>m.region))].sort(),cs=[...new Set(ms.map(m=>m.complexity))].sort(),ts=[...new Set(ms.map(m=>m.type))].sort();
fill("regionFilter",rs,"Minden tájegység");fill("complexityFilter",cs,"Minden komplexitás");fill("typeFilter",ts,"Minden típus");
["search","regionFilter","complexityFilter","typeFilter"].forEach(id=>document.getElementById(id).oninput=render);render();
if(window.QRCode)QRCode.toCanvas(location.href,{width:120,margin:1},(e,c)=>{if(!e)document.getElementById("qr").appendChild(c)});
